In [1]:
import tensorflow as tf

In [3]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11493376/11490434 [==============================] - 2s 0us/step


In [5]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

In [7]:
predictions = model(x_train[:1]).numpy()
predictions


If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.



array([[ 0.5665136 , -0.3530237 , -0.08104302, -0.96263915,  0.4190527 ,
         0.3675126 ,  0.73112696,  0.00894259, -0.07749772,  0.47718528]],
      dtype=float32)

In [8]:
tf.nn.softmax(predictions).numpy()

array([[0.14260344, 0.05685649, 0.07462765, 0.03090491, 0.12305196,
        0.11687052, 0.1681205 , 0.08165448, 0.07489269, 0.1304173 ]],
      dtype=float32)

In [9]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [10]:
loss_fn(y_train[:1], predictions).numpy()

2.1466887

In [11]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [12]:
model.fit(x_train, y_train, epochs=5)

Train on 60000 samples
Epoch 1/5
60000/60000 [==============================] - 5s 85us/sample - loss: 0.2993 - accuracy: 0.9134
Epoch 2/5
60000/60000 [==============================] - 4s 75us/sample - loss: 0.1459 - accuracy: 0.9572
Epoch 3/5
60000/60000 [==============================] - 5s 75us/sample - loss: 0.1089 - accuracy: 0.9665
Epoch 4/5
60000/60000 [==============================] - 4s 73us/sample - loss: 0.0887 - accuracy: 0.9730
Epoch 5/5
60000/60000 [==============================] - 4s 74us/sample - loss: 0.0742 - accuracy: 0.9763


In [13]:
model.evaluate(x_test,  y_test, verbose=2)

10000/1 - 1s - loss: 0.0343 - accuracy: 0.9781


[0.0676366139096208, 0.9781]

In [14]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [15]:
probability_model(x_test[:5])

<tf.Tensor: id=30017, shape=(5, 10), dtype=float32, numpy=
array([[8.2104840e-08, 1.5976509e-09, 3.2342284e-06, 2.5324407e-04,
        3.3479174e-11, 4.5093348e-08, 3.4465033e-12, 9.9973363e-01,
        3.2716798e-07, 9.4882907e-06],
       [1.2501316e-09, 2.5535712e-05, 9.9997151e-01, 2.9896848e-06,
        5.8325958e-19, 5.3319082e-09, 4.2267451e-13, 2.1876095e-13,
        4.7246198e-09, 7.8990312e-15],
       [2.2367938e-07, 9.9859434e-01, 3.7194564e-04, 7.0263595e-06,
        2.6574771e-05, 4.2671337e-07, 9.5505920e-06, 6.9727842e-04,
        2.9205321e-04, 5.8619730e-07],
       [9.9921548e-01, 4.7779445e-06, 2.9064808e-04, 2.8633829e-06,
        8.2407320e-07, 2.5292459e-06, 2.6798085e-04, 4.6545756e-05,
        8.3227854e-07, 1.6747230e-04],
       [4.6105270e-05, 1.5447321e-07, 1.5249167e-05, 1.6887958e-06,
        9.9514765e-01, 5.7010507e-06, 3.7748887e-05, 5.6450802e-04,
        4.8517424e-05, 4.1326177e-03]], dtype=float32)>